### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by fschuetz04** [fschuetz04/jafe-calendar#2]
- [x] Fix entry editing being susceptible to XSS
- [x] Provide feedback when reaching the maximum length of an input
- [x] Warn the user when the device is offline, currently new entries are discarded in this case
- [x] Check whether the end date comes after the start date and warn the user if that is not the case
- [x] Check whether the uploaded image has the right file type and is small enough

**Comment by dotlambda** [comment]
Example for XSS: Use
```
<a class=button onclick="alert('pwnd');">Click</a>
```
as location.

**Comment by fschuetz04** [comment]
Task 1 done with 0a7df1.

**Comment by fschuetz04** [comment]
Task 5 done with 18ea947fb556db8336b5262c08af7e78452a15a9.
